import React, { createContext, useContext, useState } from "react";

type Lang = "FR" | "EN";

const translations = {
  FR: {
    login: {
      title: "Bienvenue",
      subtitle: "Entrez vos identifiants pour accéder au panel",
      email: "Email",
      password: "Mot de passe",
      forgotPassword: "Mot de passe oublié ?",
      submit: "Se connecter",
      submitting: "Connexion...",
      noAccount: "Pas encore de compte ?",
      signUp: "S'inscrire",
    },
    signup: {
      title: "Créer un compte",
      subtitle: "Rejoindre le Nexus Dashboard",
      username: "Nom d'utilisateur",
      email: "Email",
      password: "Mot de passe",
      submit: "S'inscrire",
      submitting: "Création...",
      hasAccount: "Déjà un compte ?",
      signIn: "Se connecter",
      successTitle: "Vérifiez votre email",
      successText: "Nous avons envoyé un lien de confirmation à",
      successSub: "Cliquez dessus pour activer votre compte.",
      backToLogin: "Retour à la connexion",
    },
    forgot: {
      title: "Réinitialisation",
      subtitle: "Entrez votre email pour recevoir un lien de réinitialisation",
      email: "Email",
      submit: "Envoyer le lien",
      submitting: "Envoi...",
      successMsg: "Un lien de réinitialisation a été envoyé à votre adresse email.",
      successSub: "Vérifiez votre boîte de réception (et les spams).",
      returnToLogin: "Retour à la connexion",
      rememberPassword: "Vous vous en souvenez ?",
      signIn: "Se connecter",
    },
    nav: {
      dashboard: "Tableau de bord",
      spotify: "Lecteur Spotify",
      discord: "Bot Discord",
      analytics: "Analytiques",
      security: "Sécurité",
      database: "Base de données",
      logs: "Journaux système",
      profile: "Profil",
      settings: "Paramètres",
      logout: "Déconnexion",
    },
    dashboard: {
      welcome: "Bon retour,",
      subtitle: "Voici ce qui se passe avec vos projets aujourd'hui.",
      systemStatus: "Statut Système",
      securityLevel: "Niveau de Sécurité",
      totalUsers: "Utilisateurs",
      apiLatency: "Latence API",
      online: "En ligne",
      maximum: "Maximum",
      systemLoad: "Charge Système",
      hardwareStatus: "Matériel",
      cpuUsage: "Utilisation CPU",
      memory: "Mémoire",
      storage: "Stockage",
      recentActivity: "Activité Récente",
      noActivity: "Aucune activité récente",
      quickActions: "Actions Rapides",
      generateReport: "Générer un rapport",
      restartServices: "Redémarrer les services",
    },
    spotify: {
      title: "Intégration Spotify",
      subtitle: "Recherchez et gérez votre musique",
      connected: "Connecté",
      connectTitle: "Connecter Spotify",
      connectDesc: "Liez votre compte Spotify pour rechercher des titres, gérer des playlists et contrôler la lecture depuis le tableau de bord.",
      configRequired: "Configuration Requise",
      configDesc: "Spotify est très strict sur les URIs de redirection. Vous DEVEZ ajouter ces URLs exactes à votre tableau de bord Spotify Developer.",
      devUrl: "URL Dev :",
      prodUrl: "URL Production :",
      connectBtn: "Connecter avec Spotify",
      searchPlaceholder: "Rechercher des titres, artistes ou albums...",
      search: "Rechercher",
      reconnect: "Reconnexion requise",
      reconnectDesc: "Veuillez reconnecter votre compte Spotify pour activer les nouvelles fonctionnalités de lecture.",
      reconnectBtn: "Reconnecter Spotify",
      addedToPlaylist: "Ajouté à la playlist Nexus Dashboard !",
      failedToPlay: "Échec de la lecture. Assurez-vous d'avoir un appareil Spotify actif.",
      exitFullscreen: "Quitter le grand écran",
      lyrics: "Paroles",
      lyricsNotFound: "Paroles introuvables.",
    },
    discord: {
      title: "Panneau de contrôle Discord",
      subtitle: "Gérez l'activité du bot et envoyez des messages",
      botOnline: "Bot En Ligne",
      botOffline: "Bot Hors Ligne",
      notConfigured: "Non Configuré",
      broadcastTitle: "Message de Diffusion",
      messageLabel: "Contenu du message",
      messagePlaceholder: "Tapez un message à envoyer sur le canal Discord...",
      sendBtn: "Envoyer au canal",
      logsTitle: "Journaux récents",
      refresh: "Actualiser",
      loading: "Chargement...",
      noMessages: "Aucun message récent",
      configTitle: "Configuration requise",
      configDesc: "Le bot Discord n'est pas configuré. Veuillez ajouter vos secrets dans les paramètres.",
      configToken: "DISCORD_BOT_TOKEN",
      configChannel: "DISCORD_CHANNEL_ID",
    },
    analytics: {
      title: "Aperçu Analytique",
      subtitle: "Plongez dans les métriques de performance de votre système.",
      totalTraffic: "Trafic Total",
      activeUsers: "Utilisateurs Actifs",
      conversionRate: "Taux de Conversion",
      avgLatency: "Latence Moy.",
      trafficTrends: "Tendances du Trafic",
      pageViews: "Vues de Page",
    },
    database: {
      title: "Gestion Base de Données",
      subtitle: "Surveillez et gérez vos instances de base de données",
      connected: "Connecté",
      totalSize: "Taille Totale",
      totalUsers: "Utilisateurs",
      uptime: "Disponibilité",
      recentQueries: "Requêtes Récentes",
      query: "Requête",
      duration: "Durée",
      status: "Statut",
      timestamp: "Horodatage",
      loading: "Chargement...",
    },
    security: {
      title: "Centre de Sécurité",
      subtitle: "Gérez la sécurité de votre compte et les paramètres d'authentification",
      twoFaTitle: "Authentification à Deux Facteurs",
      twoFaDesc: "Ajoutez une couche de sécurité supplémentaire en activant la 2FA par email.",
      emailTwoFa: "2FA par Email",
      emailTwoFaDesc: "Recevoir des codes par email",
      setup: "Configurer",
      enable: "Activer",
      disable: "Désactiver",
      cancel: "Annuler",
      twoFaEnabled: "2FA par Email Activé",
      twoFaEnabledDesc: "Codes envoyés à",
      twoFaConfirmDesc: "Voulez-vous activer la 2FA par email ? Les codes seront envoyés à",
      passwordTitle: "Gestion du Mot de Passe",
      currentPassword: "Mot de passe actuel",
      newPassword: "Nouveau mot de passe",
      updatePassword: "Mettre à jour le mot de passe",
      sessionsTitle: "Sessions Actives",
      currentDevice: "Appareil actuel",
      revoke: "Révoquer",
    },
    profile: {
      title: "Profil Utilisateur",
      subtitle: "Gérez vos informations personnelles et la sécurité.",
      administrator: "Administrateur",
      accountStatus: "Statut du compte",
      verified: "Vérifié",
      personalInfo: "Informations Personnelles",
      username: "Nom d'utilisateur",
      email: "Adresse Email",
      securitySection: "Sécurité & 2FA",
      currentPassword: "Mot de passe actuel",
      discordId: "ID Discord (Pour la 2FA)",
      discordIdPlaceholder: "ex. 123456789012345678",
      testBtn: "Tester",
      saveBtn: "Sauvegarder",
      saving: "Sauvegarde...",
      savedOk: "Profil mis à jour avec succès !",
      passwordUpdated: "Mot de passe mis à jour !",
      testSent: "Message de test envoyé !",
      testFailed: "Échec du test. Vérifiez l'ID et la config du bot.",
    },
    settings: {
      title: "Paramètres Système",
      subtitle: "Configurez votre expérience Nexus Dashboard.",
      appearance: "Apparence",
      notifications: "Notifications",
      privacy: "Confidentialité & Sécurité",
      dataManagement: "Gestion des Données",
      theme: "Thème",
      animations: "Animations",
      pushNotifications: "Notifications Push",
      emailAlerts: "Alertes Email",
      twoFactorAuth: "Auth. à deux facteurs",
      enable2fa: "Activer la 2FA",
      sessionTimeout: "Délai d'expiration session",
      autoBackup: "Sauvegarde automatique",
      clearCache: "Vider le cache",
      clearNow: "Vider maintenant",
      min15: "15 minutes",
      hour1: "1 heure",
      never: "Jamais",
    },
    logs: {
      title: "Journaux Système",
      subtitle: "Activité et événements en temps réel",
      refresh: "Actualiser",
      clear: "Vider",
      filter: "Filtrer",
      all: "Tous",
      info: "Info",
      success: "Succès",
      warning: "Avertissement",
      error: "Erreur",
      noLogs: "Aucun journal trouvé",
    },
  },
  EN: {
    login: {
      title: "Welcome Back",
      subtitle: "Enter your credentials to access the panel",
      email: "Email",
      password: "Password",
      forgotPassword: "Forgot password?",
      submit: "Sign In",
      submitting: "Signing in...",
      noAccount: "Don't have an account?",
      signUp: "Sign up",
    },
    signup: {
      title: "Create Account",
      subtitle: "Join Nexus Dashboard today",
      username: "Username",
      email: "Email",
      password: "Password",
      submit: "Sign Up",
      submitting: "Creating account...",
      hasAccount: "Already have an account?",
      signIn: "Sign in",
      successTitle: "Check your email",
      successText: "We've sent a confirmation link to",
      successSub: "Please click it to activate your account.",
      backToLogin: "Back to login",
    },
    forgot: {
      title: "Reset Password",
      subtitle: "Enter your email to receive a reset link",
      email: "Email",
      submit: "Send Reset Link",
      submitting: "Sending...",
      successMsg: "A reset link has been sent to your email address.",
      successSub: "Check your inbox (and spam folder) for the link.",
      returnToLogin: "Return to Login",
      rememberPassword: "Remember your password?",
      signIn: "Sign in",
    },
    nav: {
      dashboard: "Dashboard",
      spotify: "Spotify Player",
      discord: "Discord Bot",
      analytics: "Analytics",
      security: "Security",
      database: "Database",
      logs: "System Logs",
      profile: "Profile",
      settings: "Settings",
      logout: "Logout",
    },
    dashboard: {
      welcome: "Welcome back,",
      subtitle: "Here's what's happening with your projects today.",
      systemStatus: "System Status",
      securityLevel: "Security Level",
      totalUsers: "Total Users",
      apiLatency: "API Latency",
      online: "Online",
      maximum: "Maximum",
      systemLoad: "System Load Overview",
      hardwareStatus: "Hardware Status",
      cpuUsage: "CPU Usage",
      memory: "Memory",
      storage: "Storage",
      recentActivity: "Recent Activity",
      noActivity: "No recent activity",
      quickActions: "Quick Actions",
      generateReport: "Generate Analytics Report",
      restartServices: "Restart Services",
    },
    spotify: {
      title: "Spotify Integration",
      subtitle: "Search and manage your music",
      connected: "Connected",
      connectTitle: "Connect Spotify",
      connectDesc: "Link your Spotify account to search tracks, manage playlists, and control playback directly from the dashboard.",
      configRequired: "Configuration Required",
      configDesc: "Spotify is extremely strict about Redirect URIs. You MUST add these exact URLs to your Spotify Developer Dashboard.",
      devUrl: "Dev URL:",
      prodUrl: "Production URL:",
      connectBtn: "Connect with Spotify",
      searchPlaceholder: "Search for tracks, artists, or albums...",
      search: "Search",
      reconnect: "Action Required: Update Permissions",
      reconnectDesc: "We've added new player features! Please reconnect your Spotify account to grant the necessary playback permissions.",
      reconnectBtn: "Reconnect Spotify",
      addedToPlaylist: "Added to Nexus Dashboard playlist!",
      failedToPlay: "Failed to play. Ensure you have an active Spotify device open.",
      exitFullscreen: "Exit fullscreen",
      lyrics: "Lyrics",
      lyricsNotFound: "Lyrics not found.",
    },
    discord: {
      title: "Discord Control Panel",
      subtitle: "Manage bot activity and send messages",
      botOnline: "Bot Online",
      botOffline: "Bot Offline",
      notConfigured: "Not Configured",
      broadcastTitle: "Broadcast Message",
      messageLabel: "Message Content",
      messagePlaceholder: "Type a message to send to the Discord channel...",
      sendBtn: "Send to Channel",
      logsTitle: "Recent Logs",
      refresh: "Refresh",
      loading: "Loading...",
      noMessages: "No recent messages",
      configTitle: "Configuration Required",
      configDesc: "The Discord bot is not configured. Please add your secrets in the settings.",
      configToken: "DISCORD_BOT_TOKEN",
      configChannel: "DISCORD_CHANNEL_ID",
    },
    analytics: {
      title: "Analytics Overview",
      subtitle: "Deep dive into your system's performance metrics.",
      totalTraffic: "Total Traffic",
      activeUsers: "Active Users",
      conversionRate: "Conversion Rate",
      avgLatency: "Avg. Latency",
      trafficTrends: "Traffic Trends",
      pageViews: "Page Views",
    },
    database: {
      title: "Database Management",
      subtitle: "Monitor and manage your database instances",
      connected: "Connected",
      totalSize: "Total Size",
      totalUsers: "Total Users",
      uptime: "Uptime",
      recentQueries: "Recent Queries",
      query: "Query",
      duration: "Duration",
      status: "Status",
      timestamp: "Timestamp",
      loading: "Loading...",
    },
    security: {
      title: "Security Center",
      subtitle: "Manage your account security and authentication settings",
      twoFaTitle: "Two-Factor Authentication",
      twoFaDesc: "Add an extra layer of security to your account by enabling two-factor authentication via Email.",
      emailTwoFa: "Email 2FA",
      emailTwoFaDesc: "Receive codes via email",
      setup: "Setup",
      enable: "Enable",
      disable: "Disable",
      cancel: "Cancel",
      twoFaEnabled: "Email 2FA Enabled",
      twoFaEnabledDesc: "Codes sent to",
      twoFaConfirmDesc: "Are you sure you want to enable Email 2FA? Codes will be sent to",
      passwordTitle: "Password Management",
      currentPassword: "Current Password",
      newPassword: "New Password",
      updatePassword: "Update Password",
      sessionsTitle: "Active Sessions",
      currentDevice: "Current Device",
      revoke: "Revoke",
    },
    profile: {
      title: "User Profile",
      subtitle: "Manage your personal information and security.",
      administrator: "Administrator",
      accountStatus: "Account Status",
      verified: "Verified",
      personalInfo: "Personal Information",
      username: "Username",
      email: "Email Address",
      securitySection: "Security & 2FA",
      currentPassword: "Current Password",
      discordId: "Discord User ID (For 2FA)",
      discordIdPlaceholder: "e.g. 123456789012345678",
      testBtn: "Test",
      saveBtn: "Save Changes",
      saving: "Saving...",
      savedOk: "Profile updated successfully!",
      passwordUpdated: "Password updated!",
      testSent: "Test message sent successfully!",
      testFailed: "Failed to send test message. Check your User ID and bot configuration.",
    },
    settings: {
      title: "System Settings",
      subtitle: "Configure your Nexus Dashboard experience.",
      appearance: "Appearance",
      notifications: "Notifications",
      privacy: "Privacy & Security",
      dataManagement: "Data Management",
      theme: "Theme",
      animations: "Animations",
      pushNotifications: "Push Notifications",
      emailAlerts: "Email Alerts",
      twoFactorAuth: "Two-Factor Auth",
      enable2fa: "Enable 2FA",
      sessionTimeout: "Session Timeout",
      autoBackup: "Auto-Backup",
      clearCache: "Clear Cache",
      clearNow: "Clear Now",
      min15: "15 mins",
      hour1: "1 hour",
      never: "Never",
    },
    logs: {
      title: "System Logs",
      subtitle: "Real-time activity and events",
      refresh: "Refresh",
      clear: "Clear",
      filter: "Filter",
      all: "All",
      info: "Info",
      success: "Success",
      warning: "Warning",
      error: "Error",
      noLogs: "No logs found",
    },
  },
};

type Translations = typeof translations.FR;

interface LanguageContextType {
  lang: Lang;
  t: Translations;
  toggle: () => void;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    return (localStorage.getItem("nexus-lang") as Lang) || "FR";
  });

  const toggle = () => {
    setLang((prev) => {
      const next = prev === "FR" ? "EN" : "FR";
      localStorage.setItem("nexus-lang", next);
      return next;
    });
  };

  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], toggle }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
